// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';
const { MOLY_API_KEY } = process.env;
// Generated by https://quicktype.io

export interface Data {
	book: Book;
}

export interface Book {
	id: number;
	authors: Author[];
	editors: any[];
	title: string;
	subtitle: string;
	cover: string;
	description: string;
	url: string;
	tags: Author[];
	like_average: number;
	like_count: number;
	reviews_count: number;
	citations_count: number;
	year_of_publishing: number;
}

export interface Author {
	id: number;
	name: string;
}


export default async function handler(
	req: NextApiRequest,
	res: NextApiResponse<Data>
) {
	const { id } = req.query;
	const _res = await fetch(`https://moly.hu/api/book/${id}.json?key=${MOLY_API_KEY}`)
	const { book } = await _res.json()
	res.status(200).json(book)
}
